### ISSUE TITLE
Add autocomplete for extras + turbo

### ISSUE THREAD

**Issue by daftspunk** [SergeyKasyanov/vscode-october-extension#1]
Thanks for the great extension! I even see some inspiration from the [YAML work done by Inetis](https://github.com/inetis-ch/october-schemas).

One suggestion to add in the autocomplete is the possibility to use AJAX extras and turbo in the same call, something like this.

```twig
{% framework extras turbo %}
```

**Comment by SergeyKasyanov** [comment]
Hi.

Added {% framework extras turbo %} snippet in 0.7.1.

Didn't know about https://github.com/inetis-ch/october-schemas :smile:
