### ISSUE TITLE
The extension doesn't respect new lines or single/double quotes when formatting a Twig file

### ISSUE THREAD

**Issue by davidkvasnovsky** [SergeyKasyanov/vscode-october-extension#15]
### Description
There appears to be an issue with the extension when formatting Twig files. Specifically, the extension does not respect new lines or single/double quotes.

### Steps to Reproduce
1. Open a Twig file.
2. Apply formatting using the extension.

### Expected Behavior
The formatted file should maintain new lines and the integrity of single/double quotes.

### Actual Behavior
After formatting, the new lines and single/double quotes are not preserved correctly.

### Proposed Solution
It would be beneficial to have an option to control the formatting behavior regarding new lines and quotes. This could provide flexibility according to different users' needs.

#### Before formatting:
<img width="546" alt="image" src="https://github.com/SergeyKasyanov/vscode-october-extension/assets/12381721/1950cc3c-6369-4a94-a4f4-af86993072f5">

#### After formatting:
<img width="542" alt="image" src="https://github.com/SergeyKasyanov/vscode-october-extension/assets/12381721/1e1025d5-ce7d-4950-9603-fd89f6248cc9">

**Comment by SergeyKasyanov** [comment]
Hello. Just published new version (0.25). Single/double quotes now should preserve correctly.

**Comment by SergeyKasyanov** [comment]
Hello. Check out 0.29.0. I made some improvements in formatting, also OctoberCode now support .prettierrc config files, so you can change some formatting behavior by this.
