### ISSUE TITLE
Location of trigger reference

### ISSUE THREAD

**Issue by daftspunk** [SergeyKasyanov/vscode-october-extension#3]
Some changes are needed, but I can't find where the _$refs/defintions/Trigger_ reference is stored for a pull request.

![image](https://user-images.githubusercontent.com/1392869/193394806-b7bfe7c2-a8c4-43b7-9229-cb3bc1ffac79.png)

Changes required as in the screenshot:

- New action called `fill`, which can check a field or set to the `fill[somevalue]` to a specific value
- It is possible to have multiple actions separated by a `|` pipe character

**Comment by SergeyKasyanov** [comment]
For yaml schemas I use [this](https://github.com/SergeyKasyanov/october-schemas)
