### ISSUE TITLE
File type label super long

### ISSUE THREAD

**Issue by daftspunk** [SergeyKasyanov/vscode-october-extension#4]
One thing I noticed is the YAML syntax shows a document type of `file://path/to/my/profile/.vscode/extensions/.../schemas/fields.yaml.json`, which is unusual since others are a file name or have some custom label.

![image](https://user-images.githubusercontent.com/1392869/193395094-74ddd3da-4814-4686-be95-0c0c311996e4.png)

Is it missing a label somewhere?

**Comment by SergeyKasyanov** [comment]
It would be cool, but I didn't find anything about schemas labels in [redhat yaml extension repo](https://github.com/redhat-developer/vscode-yaml)

**Comment by SergeyKasyanov** [comment]
Check out 0.29.0. Now it shows label correctly

**Comment by daftspunk** [comment]
Nice, you did it!
