### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by artistro08** [SergeyKasyanov/vscode-october-extension#5]
For twig, code folding would be amazing. Right now, it doesn't have and fold markers. Picture for reference. 

![image](https://user-images.githubusercontent.com/6427230/193415617-f56f1f4f-061b-40e0-8d3d-caa597415454.png)

**Comment by SergeyKasyanov** [comment]
You can update VSCode to latest version (October 2022 (version 1.73)) and add this to config
```
"[october-tpl]": {
    "editor.defaultFoldingRangeProvider": "SergeyKasyanov.october-code"
}
```

**Comment by artistro08** [comment]
Awesome, works like a charm!
