### ISSUE TITLE
Creating Brackets in quotes creates extra brackets

### ISSUE THREAD

**Issue by artistro08** [SergeyKasyanov/vscode-october-extension#6]
So when I create twig brackets (`{% %}` and `{{ }}`) inside single or double quotes, it creates a second set of brackets (`{{` and `{%` ) inside the quotes. 

I've been able to reproduce pretty consistently.

**Comment by SergeyKasyanov** [comment]
Hello. Fixed in v0.7.5.

**Comment by artistro08** [comment]
You're amazing! Thank you!
