### ISSUE TITLE
Error Underlines are slightly off

### ISSUE THREAD

**Issue by artistro08** [SergeyKasyanov/vscode-october-extension#7]
Error underlines are a tad off. Screenshot for reference: 
![image](https://user-images.githubusercontent.com/6427230/193415880-0c03fba0-d872-4a85-84a3-e9848c742ed1.png)

**Comment by SergeyKasyanov** [comment]
Hello. Can you check the new version (0.9.0) and see if problem still exists?

**Comment by artistro08** [comment]
Verified fixed as far as I can see. Thank you!
