### ISSUE TITLE
Missing Template Errors Should Account for Child Themes

### ISSUE THREAD

**Issue by artistro08** [SergeyKasyanov/vscode-october-extension#8]
So I get errors when template files are missing throughout the project. The problem is, the templates that are missing are dependent on parent theme. 

This extension should check to see if the current file in the theme folder is a child theme. After that, it should look for other template files in the respective directories of the parent theme.

**Comment by SergeyKasyanov** [comment]
Support for parent/child themes added to version 0.9.0
