### ISSUE TITLE
In themes it does not detect partials, templates or pages that are in subfolders

### ISSUE THREAD

**Issue by Davox08** [SergeyKasyanov/vscode-october-extension#9]
![01](https://user-images.githubusercontent.com/42631079/197864454-c1740907-55a4-4ac8-ac38-fd77ae8b24f0.jpg)
![02](https://user-images.githubusercontent.com/42631079/197864460-2158ee22-08fe-4a1b-93c0-36efd7dd7c6d.jpg)

Thank you very much for your excellent work, I loved it.

I have a problem with theme development. Apparently it doesn't detect layouts, partials or pages when they are in subfolders:
 
- Detects them fine if they are not in subfolders
- If you apply the suggested fix, it overwrites the original file and detects it fine, but when you restart Visual Studio the problem reoccurs.
- If you enter each file that it is not detecting and save it even if it has no changes, it detects them well but when you restart the program this error occurs again.
- I tried on a clean install of VS Code but got the same error. 

Do I have to install any extra extensions or fix something in my configuration?

**Comment by SergeyKasyanov** [comment]
Hello. Can you check the new version (0.9.0) and see if problem still exists?

**Comment by Davox08** [comment]
![Captura de pantalla 2023-01-29 144334](https://user-images.githubusercontent.com/42631079/215354781-f21cc518-8143-4d26-bdd8-78df710cb544.jpg)

Thanks! This issue is fixed. I'm using the **v0.10.0**

I noticed that the theme development function: _Completions of theme file names: layouts, pages, partials, content files_ is disabled. 

Is this a bug or is there something I need to do to enable this feature?

**Comment by SergeyKasyanov** [comment]
Hello. No, completions is not disabled 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/9932569/215397487-956f8e1a-a1ce-48a7-be6c-6364c8755001.png">
